# Project metadata
[project]
name = "screeenly"

# Use buildpacks to manage deployment
[build]
builder = "heroku/buildpacks:20"
buildpacks = ["heroku/php", "heroku/nodejs"]

# Steps during the build process
[build.steps]
steps = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run prod",
  "php artisan key:generate",
  "php artisan migrate --force"
]

# Environment variables for the application
[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "debug"

# Start the application using Apache and PHP-FPM
[start]
command = "vendor/bin/heroku-php-apache2 public/"
