# Project metadata
[project]
name = "screeenly"

# Define build steps to execute (during deployment)
[build]
steps = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run prod",
  "php artisan key:generate",
  "php artisan migrate --force"
  "rm -f /nix/store/*yarn/LICENSE"
]

# Define environment variables for the application
[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "debug"

# Start the application using Apache and PHP-FPM
[start]
command = "vendor/bin/heroku-php-apache2 public/"