[build]
steps = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run prod",
  "php artisan key:generate",
  "php artisan migrate --force"
]

[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "debug"
