
[build]
builder = "heroku/buildpacks:20"

[build.steps]
   command = "composer install --no-dev --optimize-autoloader"
   command = "npm install"
   command = "npm run prod"
   command = "php artisan key:generate"
   command = "php artisan migrate --force"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  DB_CONNECTION = "mysql"
  DB_HOST = "127.0.0.1"
  DB_PORT = "3306"
  DB_DATABASE = "railway"
  DB_USERNAME = "root"
  DB_PASSWORD = "password"

[deploy]
region = "us-east4"
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10[project]
name = "screeenly"

[plugins]
mysql = { startCommand = "docker run --name mysql -e MYSQL_ROOT_PASSWORD=password -d mysql:5.7" }


[start]
  command = "php artisan serve --host=0.0.0.0 --port=8000"
